CREATE TABLE ITEM (
  ID INTEGER  NOT NULL  ,
  SHORT_DESCR VARCHAR(100)  NOT NULL  ,
  LONG_DESCR VARCHAR(1000)    ,
  CATEGORY VARCHAR(30)    ,
  SALE_PRICE INTEGER    ,
  PURCHASE_PRICE INTEGER    ,
  QUANTITY INTEGER      ,
PRIMARY KEY(ID));



CREATE TABLE SUPPLIER (
  ID INTEGER  NOT NULL  ,
  LNAME VARCHAR(30)  NOT NULL  ,
  POSTAL_CODE VARCHAR(15)    ,
  CITY VARCHAR(30)    ,
  AREA VARCHAR(30)    ,
  STREET VARCHAR(30)    ,
  STREET_NUMBER VARCHAR(10)      ,
PRIMARY KEY(ID));



CREATE TABLE EMPLOYEE (
  ID INTEGER  NOT NULL  ,
  LNAME VARCHAR(30)  NOT NULL  ,
  FNAME VARCHAR(30)    ,
  POSTAL_CODE VARCHAR(15)    ,
  CITY VARCHAR(30)    ,
  AREA VARCHAR(30)    ,
  STREET VARCHAR(30)    ,
  STREET_NUMBER VARCHAR(10)    ,
  PHONE VARCHAR(10)    ,
  VAT VARCHAR(30)    ,
  AT VARCHAR(30)      ,
PRIMARY KEY(ID));



CREATE TABLE CUSTOMER (
  ID INTEGER  NOT NULL  ,
  LNAME VARCHAR(15)  NOT NULL  ,
  POSTAL_CODE VARCHAR(15)    ,
  CITY VARCHAR(30)    ,
  AREA VARCHAR(30)    ,
  STREET VARCHAR(30)    ,
  STREET_NUMBER VARCHAR(10)      ,
PRIMARY KEY(ID));



CREATE TABLE SUPPLIER_PHONES (
  SUPPLIER_ID INTEGER  NOT NULL  ,
  PHONE VARCHAR(30)  NOT NULL    ,
PRIMARY KEY(SUPPLIER_ID, PHONE)  ,
  FOREIGN KEY(SUPPLIER_ID)
    REFERENCES SUPPLIER(ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION);


CREATE INDEX SUPPLIER_PHONES_FKIndex1 ON SUPPLIER_PHONES (SUPPLIER_ID);



CREATE TABLE CUSTOMER_PHONES (
  CUSTOMER_ID INTEGER  NOT NULL  ,
  PHONE VARCHAR(30)  NOT NULL    ,
PRIMARY KEY(CUSTOMER_ID, PHONE)  ,
  FOREIGN KEY(CUSTOMER_ID)
    REFERENCES CUSTOMER(ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION);


CREATE INDEX CUSTOMER_PHONES_FKIndex1 ON CUSTOMER_PHONES (CUSTOMER_ID);



CREATE TABLE PURCHASE (
  ID INTEGER  NOT NULL  ,
  ITEM_ID INTEGER  NOT NULL  ,
  SUPPLIER_ID INTEGER  NOT NULL  ,
  EMPLOYEE_ID INTEGER  NOT NULL  ,
  DATE DATE    ,
  QUANTITY INTEGER    ,
  ITEM_PRICE INTEGER    ,
  TOTAL_PRICE INTEGER      ,
PRIMARY KEY(ID)    ,
  FOREIGN KEY(EMPLOYEE_ID)
    REFERENCES EMPLOYEE(ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(SUPPLIER_ID)
    REFERENCES SUPPLIER(ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(ITEM_ID)
    REFERENCES ITEM(ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION);


CREATE INDEX PURCHASE_FKIndex3 ON PURCHASE (SUPPLIER_ID);
CREATE INDEX PURCHASE_FKindex1 ON PURCHASE (EMPLOYEE_ID);



CREATE TABLE SALE (
  ID INTEGER  NOT NULL  ,
  ITEM_ID INTEGER  NOT NULL  ,
  CUSTOMER_ID INTEGER  NOT NULL  ,
  EMPLOYEE_ID INTEGER  NOT NULL  ,
  DATE DATE    ,
  QUANTITY INTEGER    ,
  ITEM_PRICE INTEGER    ,
  TOTAL_PRICE INTEGER      ,
PRIMARY KEY(ID)    ,
  FOREIGN KEY(EMPLOYEE_ID)
    REFERENCES EMPLOYEE(ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(CUSTOMER_ID)
    REFERENCES CUSTOMER(ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(ITEM_ID)
    REFERENCES ITEM(ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION);


CREATE INDEX SALE_FKIndex2 ON SALE (EMPLOYEE_ID);
CREATE INDEX SALE_FKIndex3 ON SALE (CUSTOMER_ID);




